import { Product } from "@/types";

export const productsData: Product[] = [


  {
    id: "iphone-13",
    name: "iPhone 13",
    category: "iphone",
    price: 599.99,
    originalPrice: 699.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd?w=500",
    description: "Advanced dual-camera system with sensor-shift stabilization.",
    features: [
      "A15 Bionic chip",
      "6.1-inch Super Retina XDR display",
      "Advanced dual-camera system",
      "Cinematic mode video",
    ],
    inStock: true,
    stockQuantity: 35,
    tags: ["iphone", "a15", "cinematic-mode", "popular", "13", "series-13"],
    rating: 4.6,
    reviews: 312,
  },
  {
    id: "iphone-13-pro",
    name: "iPhone 13 Pro",
    category: "iphone",
    price: 799.99,
    originalPrice: 899.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/79/fc/24/79fc24ffa907ae4239f3e8a32571d9c0.jpg",
    description: "Pro camera system with macro photography and ProMotion.",
    features: [
      "A15 Bionic chip with 5-core GPU",
      "ProMotion technology with 120Hz",
      "Pro camera system with macro",
      "1TB storage option",
    ],
    inStock: true,
    stockQuantity: 22,
    tags: ["iphone", "pro", "promotion", "macro", "13-pro", "series-13"],
    rating: 4.8,
    reviews: 189,
  },
  {
    id: "iphone-13-pro-max",
    name: "iPhone 13 Pro Max",
    category: "iphone",
    price: 899.99,
    originalPrice: 999.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/1a/7e/ee/1a7eeef17d279f2da4d80346ca04335a.jpg",
    description: "Largest iPhone 13 display with best battery life ever.",
    features: [
      "A15 Bionic chip with 5-core GPU",
      "6.7-inch Super Retina XDR display",
      "Pro camera system with sensor-shift",
      "Best battery life in iPhone",
    ],
    inStock: true,
    stockQuantity: 18,
    tags: ["iphone", "pro-max", "large-display", "long-battery", "13-pro-max", "series-13"],
    rating: 4.7,
    reviews: 198,
  },

  // iPhone 14 Series
  {
    id: "iphone-14",
    name: "iPhone 14",
    category: "iphone",
    price: 699.99,
    originalPrice: 799.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1664478546384-d57ffe74a78c?w=500",
    description: "Advanced safety features with crash detection and emergency SOS.",
    features: [
      "A15 Bionic chip",
      "6.1-inch Super Retina XDR display",
      "Crash Detection and Emergency SOS",
      "Improved battery life",
    ],
    inStock: true,
    stockQuantity: 28,
    tags: ["iphone", "safety", "crash-detection", "reliable", "14", "series-14"],
    rating: 4.5,
    reviews: 267,
  },
  {
    id: "iphone-14-pro",
    name: "iPhone 14 Pro",
    category: "iphone",
    price: 899.99,
    originalPrice: 999.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/b0/01/d8/b001d8adf3c5f20c3f9edada04df632e.jpg",
    description: "Dynamic Island and Always-On display with 48MP main camera.",
    features: [
      "A16 Bionic chip",
      "Dynamic Island and Always-On display",
      "48MP Main camera with quad-pixel sensor",
      "Action mode for video",
    ],
    inStock: true,
    stockQuantity: 16,
    tags: ["iphone", "pro", "dynamic-island", "48mp", "14-pro", "series-14"],
    rating: 4.7,
    reviews: 223,
  },
  {
    id: "iphone-14-pro-max",
    name: "iPhone 14 Pro Max",
    category: "iphone",
    price: 999.99,
    originalPrice: 1099.99,
    currency: "USD",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyx-cccmUJCTTerlWhF5X7Fy_2btAsv0HUYaT2_MEp8SiCKqEmQafus_mI9OYL8wcWz94&usqp=CAU",
    description: "Largest and most advanced iPhone with Dynamic Island.",
    features: [
      "A16 Bionic chip",
      "6.7-inch Super Retina XDR display",
      "Dynamic Island and Always-On display",
      "48MP Main camera with quad-pixel sensor",
    ],
    inStock: true,
    stockQuantity: 14,
    tags: ["iphone", "pro-max", "dynamic-island", "large-display", "14-pro-max", "series-14"],
    rating: 4.8,
    reviews: 187,
  },

  // iPhone 15 Series
  {
    id: "iphone-15",
    name: "iPhone 15",
    category: "iphone",
    price: 799.99,
    originalPrice: 899.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500",
    description: "Advanced camera system with 48MP Main and USB-C connectivity.",
    features: [
      "A16 Bionic chip",
      "6.1-inch Super Retina XDR display",
      "48MP Main camera",
      "USB-C connectivity",
    ],
    inStock: true,
    stockQuantity: 32,
    tags: ["iphone", "usb-c", "48mp", "modern", "15", "series-15"],
    rating: 4.6,
    reviews: 289,
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    category: "iphone",
    price: 999.99,
    originalPrice: 1099.99,
    currency: "USD",
    image: "https://techcrunch.com/wp-content/uploads/2023/09/iPhone-15-Pro-01.jpg",
    description: "Titanium design with Action button and advanced pro camera system.",
    features: [
      "A17 Pro chip",
      "Titanium design with Action button",
      "Pro camera system with 5x optical zoom",
      "USB 3 speeds with USB-C",
    ],
    inStock: true,
    stockQuantity: 18,
    tags: ["iphone", "pro", "titanium", "action-button", "15-pro", "series-15"],
    rating: 4.8,
    reviews: 245,
  },
  {
    id: "iphone-15-pro-max",
    name: "iPhone 15 Pro Max",
    category: "iphone",
    price: 1199.99,
    originalPrice: 1299.99,
    currency: "USD",
    image: "https://cdn.mos.cms.futurecdn.net/hgaVb9brq7aUN8S3mmWQwQ.jpg",
    description: "Most powerful iPhone with titanium design and 5x telephoto.",
    features: [
      "A17 Pro chip",
      "Titanium design with Action button",
      "5x Telephoto camera with 120mm focal length",
      "USB 3 speeds with USB-C",
    ],
    inStock: true,
    stockQuantity: 12,
    tags: ["iphone", "pro-max", "titanium", "5x-zoom", "15-pro-max", "series-15"],
    rating: 4.9,
    reviews: 176,
  },

  // iPhone 16 Series
  {
    id: "iphone-16",
    name: "iPhone 16",
    category: "iphone",
    price: 899.99,
    originalPrice: 999.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/84/bb/f5/84bbf588499cb448d0c6ff5689b32e8d.jpg",
    description: "Beautiful design with advanced features and impressive battery life.",
    features: [
      "A17 Bionic chip",
      "Advanced dual-camera system",
      "Super Retina XDR display",
      "All-day battery life",
    ],
    inStock: true,
    stockQuantity: 28,
    tags: ["iphone", "standard", "a17", "popular", "16", "series-16"],
    rating: 4.5,
    reviews: 289,
  },
  {
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    category: "iphone",
    price: 1099.99,
    originalPrice: 1199.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500",
    description: "Professional camera system and powerful performance in titanium.",
    features: [
      "A17 Pro chip with 6-core GPU",
      "Pro camera system with 48MP Main",
      "Always-On display with ProMotion",
      "Surgical-grade titanium design",
    ],
    inStock: true,
    stockQuantity: 15,
    tags: ["iphone", "pro", "titanium", "camera", "16-pro", "series-16"],
    rating: 4.7,
    reviews: 234,
  },
  {
    id: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    category: "iphone",
    price: 1199.99,
    originalPrice: 1299.99,
    currency: "USD",
    image: "https://t2.tudocdn.net/729453?w=824&h=494",
    description: "Ultimate iPhone experience with largest display and best cameras.",
    features: [
      "A17 Pro chip with 6-core GPU",
      "6.9-inch Super Retina XDR display",
      "Advanced quad-camera system",
      "Longest battery life in iPhone",
    ],
    inStock: true,
    stockQuantity: 10,
    tags: ["iphone", "pro-max", "largest-display", "quad-camera", "16-pro-max", "series-16"],
    rating: 4.8,
    reviews: 156,
  },

  // iPhone 17 Series
  {
    id: "iphone-17",
    name: "iPhone 17",
    category: "iphone",
    price: 999.99,
    originalPrice: 1099.99,
    currency: "USD",
    image: "https://i.pinimg.com/736x/87/a0/b9/87a0b934cc33fd2c335425ab9ef0df4d.jpg",
    description: "Advanced dual-camera system and powerful A18 chip in a beautiful design.",
    features: [
      "A18 Bionic chip with 6-core GPU",
      "Advanced dual-camera system",
      "Super Retina XDR display with ProMotion",
      "All-day battery life with fast charging",
    ],
    inStock: true,
    stockQuantity: 35,
    tags: ["iphone", "standard", "a18", "latest", "17", "series-17"],
    rating: 4.7,
    reviews: 312,
  },
  {
    id: "iphone-17-pro",
    name: "iPhone 17 Pro",
    category: "iphone",
    price: 1299.99,
    originalPrice: 1399.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/2b/33/2e/2b332ea23d6d65be2b257c3004f1c6f1.jpg",
    images: [
      "https://i.pinimg.com/736x/83/88/11/8388112b4b5f47e18f34500209da3e6f.jpg",
      "https://i.pinimg.com/1200x/77/60/e1/7760e187a8fcb2c8c70e0f8c95e266d9.jpg",
    ],
    description: "The most advanced iPhone with A18 Pro chip and revolutionary camera system.",
    features: [
      "A18 Pro chip with 6-core CPU",
      "Pro camera system with 48MP Main camera",
      "Super Retina XDR display with ProMotion",
      "5G capable with mmWave",
      "Titanium design with Ceramic Shield",
    ],
    inStock: true,
    stockQuantity: 25,
    tags: ["iphone", "pro", "5g", "latest", "premium", "17-pro", "series-17"],
    rating: 4.8,
    reviews: 256,
  },
  {
    id: "iphone-17-pro-max",
    name: "iPhone 17 Pro Max",
    category: "iphone",
    price: 1399.99,
    originalPrice: 1499.99,
    currency: "USD",
    image: "https://dialognews.id/wp-content/uploads/2025/09/Spesifikasi-Lengkap-iPhone-17-Pro-Warna-Baru-Lebih-Elegan-780x470.webp",
    images: [
      "https://i.pinimg.com/736x/83/88/11/8388112b4b5f47e18f34500209da3e6f.jpg",
      "https://i.pinimg.com/1200x/77/60/e1/7760e187a8fcb2c8c70e0f8c95e266d9.jpg",
    ],
    description: "The ultimate iPhone with largest display and most advanced camera system.",
    features: [
      "A18 Pro chip with 6-core CPU",
      "7.1-inch Super Retina XDR display",
      "Revolutionary penta-camera system",
      "Satellite connectivity",
      "2-day battery life",
    ],
    inStock: true,
    stockQuantity: 8,
    tags: ["iphone", "pro-max", "satellite", "penta-camera", "17-pro-max", "series-17"],
    rating: 4.9,
    reviews: 89,
  }
,

  {
    id: "macbook-pro-16",
    name: "MacBook Pro 16-inch",
    category: "mac",
    price: 2499.99,
    originalPrice: 2699.99,
    currency: "USD",
    image: "https://i.pinimg.com/736x/38/93/cd/3893cdf7cd0ce22d4bd9afcc28917b29.jpg",
    description:
      "Supercharged by M3 Pro and M3 Max chips for next-level performance.",
    features: [
      "M3 Pro or M3 Max chip",
      "16-inch Liquid Retina XDR display",
      "Up to 128GB unified memory",
      "Up to 22 hours battery life",
    ],
    inStock: true,
    stockQuantity: 8,
    tags: ["macbook", "pro", "16-inch", "professional"],
    rating: 4.9,
    reviews: 89,
  },
  {
    id: "macbook-pro-14",
    name: "MacBook Pro 14-inch",
    category: "mac",
    price: 1999.99,
    originalPrice: 2199.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/5e/8d/b8/5e8db83fc851b0bbfe6b558ec2fd3f24.jpg",
    description:
      "Compact pro laptop with massive performance in a portable design.",
    features: [
      "M3 Pro chip",
      "14-inch Liquid Retina XDR display",
      "Up to 96GB unified memory",
      "Up to 18 hours battery life",
    ],
    inStock: true,
    stockQuantity: 15,
    tags: ["macbook", "pro", "14-inch", "portable"],
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "macbook-air-15",
    name: "MacBook Air 15-inch",
    category: "mac",
    price: 1299.99,
    originalPrice: 1399.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/d8/b9/c1/d8b9c178c4332fa5f2a09cd797ddd9fc.jpg",
    description: "Impressively big and impossibly thin with M3 chip.",
    features: [
      "M3 chip with 8-core CPU",
      "15.3-inch Liquid Retina display",
      "Up to 18 hours battery life",
      "Fanless silent design",
    ],
    inStock: true,
    stockQuantity: 25,
    tags: ["macbook", "air", "15-inch", "thin"],
    rating: 4.7,
    reviews: 267,
  },
  {
    id: "macbook-air-13",
    name: "MacBook Air 13-inch",
    category: "mac",
    price: 1099.99,
    originalPrice: 1199.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/97/01/71/97017108bcbf8bb85075b8c5aec9a43a.jpg",
    description: "The world's best consumer laptop with M3 chip.",
    features: [
      "M3 chip with 8-core CPU",
      "13.6-inch Liquid Retina display",
      "Up to 18 hours battery life",
      "Ultra-portable design",
    ],
    inStock: true,
    stockQuantity: 30,
    tags: ["macbook", "air", "13-inch", "ultra-portable"],
    rating: 4.6,
    reviews: 345,
  },
  {
    id: "imac-24",
    name: "iMac 24-inch",
    category: "mac",
    price: 1499.99,
    originalPrice: 1599.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500",
    description: "Stunning all-in-one desktop with 4.5K Retina display.",
    features: [
      "M3 chip with 8-core CPU",
      "24-inch 4.5K Retina display",
      "1080p FaceTime HD camera",
      "Six-speaker sound system",
    ],
    inStock: true,
    stockQuantity: 12,
    tags: ["imac", "desktop", "all-in-one", "retina"],
    rating: 4.7,
    reviews: 178,
  },
  {
    id: "mac-mini",
    name: "Mac Mini",
    category: "mac",
    price: 699.99,
    originalPrice: 799.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=500",
    description: "Superfast desktop with M2 chip in a compact design.",
    features: [
      "M2 chip with 8-core CPU",
      "Compact desktop design",
      "Support for up to 2 displays",
      "Advanced connectivity",
    ],
    inStock: true,
    stockQuantity: 20,
    tags: ["mac", "mini", "desktop", "compact"],
    rating: 4.5,
    reviews: 156,
  },
  {
  id: "macbook-pro-16-m3-max",
  name: "MacBook Pro 16-inch M3 Max",
  category: "mac",
  price: 3499.99,
  originalPrice: 3899.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/ef/73/97/ef7397b48de07a9b009f9a13438dfd3b.jpg",
  description: "Ultimate pro laptop with M3 Max chip for extreme performance.",
  features: [
    "M3 Max chip with 16-core CPU, 40-core GPU",
    "16-inch Liquid Retina XDR display",
    "Up to 128GB unified memory",
    "Up to 8TB SSD storage",
    "Up to 22 hours battery life"
  ],
  inStock: true,
  stockQuantity: 5,
  tags: ["macbook", "pro", "16-inch", "professional", "m3-max", "max"],
  rating: 4.9,
  reviews: 67,
},
{
  id: "macbook-pro-16-m3-pro",
  name: "MacBook Pro 16-inch M3 Pro",
  category: "mac",
  price: 2499.99,
  originalPrice: 2699.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/03/28/3f/03283f99edf88f079a18db29cf7f0fea.jpg",
  description: "Supercharged by M3 Pro chip for professional workflows.",
  features: [
    "M3 Pro chip with 12-core CPU, 18-core GPU",
    "16-inch Liquid Retina XDR display",
    "Up to 36GB unified memory",
    "Up to 4TB SSD storage",
    "Up to 22 hours battery life"
  ],
  inStock: true,
  stockQuantity: 8,
  tags: ["macbook", "pro", "16-inch", "professional", "m3-pro", "pro"],
  rating: 4.8,
  reviews: 89,
},
{
  id: "macbook-pro-14-m3-max",
  name: "MacBook Pro 14-inch M3 Max",
  category: "mac",
  price: 3199.99,
  originalPrice: 3499.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/fc/bc/87/fcbc87279f9d75ff40516bdde7e83298.jpg",
  description: "Compact powerhouse with M3 Max chip in portable design.",
  features: [
    "M3 Max chip with 14-core CPU, 30-core GPU",
    "14-inch Liquid Retina XDR display",
    "Up to 96GB unified memory",
    "Up to 8TB SSD storage",
    "Up to 18 hours battery life"
  ],
  inStock: true,
  stockQuantity: 6,
  tags: ["macbook", "pro", "14-inch", "portable", "m3-max", "max"],
  rating: 4.9,
  reviews: 45,
},
{
  id: "macbook-pro-14-m3-pro",
  name: "MacBook Pro 14-inch M3 Pro",
  category: "mac",
  price: 1999.99,
  originalPrice: 2199.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/c0/ae/c2/c0aec234d964718216094f32a3ade82a.jpg",
  description: "Compact pro laptop with massive performance.",
  features: [
    "M3 Pro chip with 11-core CPU, 14-core GPU",
    "14-inch Liquid Retina XDR display",
    "Up to 36GB unified memory",
    "Up to 4TB SSD storage",
    "Up to 18 hours battery life"
  ],
  inStock: true,
  stockQuantity: 15,
  tags: ["macbook", "pro", "14-inch", "portable", "m3-pro", "pro"],
  rating: 4.8,
  reviews: 124,
},
{
  id: "macbook-air-15-m3",
  name: "MacBook Air 15-inch M3",
  category: "mac",
  price: 1299.99,
  originalPrice: 1399.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/49/76/bd/4976bda03735b86e8e84ed741dfcf55b.jpg",
  description: "Impressively big and impossibly thin with M3 chip.",
  features: [
    "M3 chip with 8-core CPU, 10-core GPU",
    "15.3-inch Liquid Retina display",
    "Up to 24GB unified memory",
    "Up to 2TB SSD storage",
    "Up to 18 hours battery life",
    "Fanless silent design"
  ],
  inStock: true,
  stockQuantity: 25,
  tags: ["macbook", "air", "15-inch", "thin", "m3", "air"],
  rating: 4.7,
  reviews: 267,
},
{
  id: "macbook-air-13-m3",
  name: "MacBook Air 13-inch M3",
  category: "mac",
  price: 1099.99,
  originalPrice: 1199.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/40/63/f6/4063f61538d6b51675ecafad0d20cd9f.jpg",
  description: "The world's best consumer laptop with M3 chip.",
  features: [
    "M3 chip with 8-core CPU, 10-core GPU",
    "13.6-inch Liquid Retina display",
    "Up to 24GB unified memory",
    "Up to 2TB SSD storage",
    "Up to 18 hours battery life",
    "Ultra-portable design"
  ],
  inStock: true,
  stockQuantity: 30,
  tags: ["macbook", "air", "13-inch", "ultra-portable", "m3", "air"],
  rating: 4.6,
  reviews: 345,
},
{
  id: "macbook-air-15-m2",
  name: "MacBook Air 15-inch M2",
  category: "mac",
  price: 1199.99,
  originalPrice: 1299.99,
  currency: "USD",
  image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500",
  description: "Big, beautiful display with powerful M2 chip.",
  features: [
    "M2 chip with 8-core CPU, 10-core GPU",
    "15.3-inch Liquid Retina display",
    "Up to 24GB unified memory",
    "Up to 2TB SSD storage",
    "Up to 18 hours battery life"
  ],
  inStock: true,
  stockQuantity: 18,
  tags: ["macbook", "air", "15-inch", "m2", "air", "value"],
  rating: 4.6,
  reviews: 189,
},
{
  id: "macbook-air-13-m2",
  name: "MacBook Air 13-inch M2",
  category: "mac",
  price: 999.99,
  originalPrice: 1099.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/11/d5/f8/11d5f812185033ef12f7de8d4b0bd6e8.jpg",
  description: "Popular ultraportable with M2 chip performance.",
  features: [
    "M2 chip with 8-core CPU, 8-core GPU",
    "13.6-inch Liquid Retina display",
    "Up to 24GB unified memory",
    "Up to 2TB SSD storage",
    "Up to 18 hours battery life"
  ],
  inStock: true,
  stockQuantity: 22,
  tags: ["macbook", "air", "13-inch", "m2", "air", "popular"],
  rating: 4.5,
  reviews: 278,
},
{
  id: "imac-24-m3",
  name: "iMac 24-inch M3",
  category: "mac",
  price: 1499.99,
  originalPrice: 1599.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/0f/a5/66/0fa56623c3091c2a734383d979185e5c.jpg",
  description: "Stunning all-in-one desktop with 4.5K Retina display.",
  features: [
    "M3 chip with 8-core CPU, 10-core GPU",
    "24-inch 4.5K Retina display",
    "1080p FaceTime HD camera",
    "Six-speaker sound system",
    "7 vibrant colors available"
  ],
  inStock: true,
  stockQuantity: 12,
  tags: ["imac", "desktop", "all-in-one", "retina", "m3"],
  rating: 4.7,
  reviews: 178,
},
{
  id: "imac-24-m1",
  name: "iMac 24-inch M1",
  category: "mac",
  price: 1299.99,
  originalPrice: 1399.99,
  currency: "USD",
  image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500",
  description: "Colorful all-in-one with powerful M1 chip.",
  features: [
    "M1 chip with 8-core CPU, 7-core GPU",
    "24-inch 4.5K Retina display",
    "1080p FaceTime HD camera",
    "Six-speaker sound system",
    "7 vibrant colors"
  ],
  inStock: true,
  stockQuantity: 8,
  tags: ["imac", "desktop", "all-in-one", "m1", "value"],
  rating: 4.5,
  reviews: 156,
},
{
  id: "mac-mini-m2-pro",
  name: "Mac Mini M2 Pro",
  category: "mac",
  price: 1299.99,
  originalPrice: 1499.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/07/9c/fd/079cfd86f52904bcc64a6316d81411ec.jpg",
  description: "Superfast desktop with M2 Pro chip for pro workflows.",
  features: [
    "M2 Pro chip with 10-core CPU, 16-core GPU",
    "Support for up to 3 displays",
    "Up to 32GB unified memory",
    "Up to 8TB SSD storage",
    "Advanced connectivity ports"
  ],
  inStock: true,
  stockQuantity: 10,
  tags: ["mac", "mini", "desktop", "compact", "m2-pro", "pro"],
  rating: 4.7,
  reviews: 89,
},
{
  id: "mac-mini-m2",
  name: "Mac Mini M2",
  category: "mac",
  price: 599.99,
  originalPrice: 699.99,
  currency: "USD",
  image: "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?w=500",
  description: "Superfast desktop with M2 chip in a compact design.",
  features: [
    "M2 chip with 8-core CPU, 10-core GPU",
    "Support for up to 2 displays",
    "Up to 24GB unified memory",
    "Up to 2TB SSD storage",
    "Advanced connectivity"
  ],
  inStock: true,
  stockQuantity: 20,
  tags: ["mac", "mini", "desktop", "compact", "m2", "budget"],
  rating: 4.5,
  reviews: 234,
},

  // iPad Category (5 products)
  {
    id: "ipad-pro-13",
    name: "iPad Pro 13-inch",
    category: "ipad",
    price: 1299.99,
    originalPrice: 1399.99,
    currency: "USD",
    image: "https://i.pinimg.com/736x/58/10/ea/5810ea928ccfaf9398f037069fac6d19.jpg",
    description:
      "The ultimate iPad experience with M2 chip and stunning display.",
    features: [
      "M2 chip",
      "13-inch Liquid Retina XDR display",
      "Pro camera system with LiDAR",
      "Thunderbolt connectivity",
    ],
    inStock: true,
    stockQuantity: 15,
    tags: ["ipad", "pro", "13-inch", "powerful"],
    rating: 4.8,
    reviews: 134,
  },
  {
    id: "ipad-pro-11",
    name: "iPad Pro 11-inch",
    category: "ipad",
    price: 999.99,
    originalPrice: 1099.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500",
    description: "Compact pro performance with advanced features.",
    features: [
      "M2 chip",
      "11-inch Liquid Retina display",
      "Pro camera system",
      "5G capable",
    ],
    inStock: true,
    stockQuantity: 18,
    tags: ["ipad", "pro", "11-inch", "portable"],
    rating: 4.7,
    reviews: 189,
  },
  {
    id: "ipad-air-13",
    name: "iPad Air 13-inch",
    category: "ipad",
    price: 899.99,
    originalPrice: 999.99,
    currency: "USD",
    image: "https://i.pinimg.com/736x/4f/23/9e/4f239eaef1445d92c89cd9d613f54a74.jpg",
    description: "Powerful and versatile with M1 chip in colorful designs.",
    features: [
      "M1 chip",
      "13-inch Liquid Retina display",
      "Touch ID in top button",
      "5G capable",
    ],
    inStock: true,
    stockQuantity: 22,
    tags: ["ipad", "air", "13-inch", "versatile"],
    rating: 4.6,
    reviews: 223,
  },
  {
    id: "ipad-air-11",
    name: "iPad Air 11-inch",
    category: "ipad",
    price: 699.99,
    originalPrice: 799.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/10/ee/0b/10ee0bc7ab78f7d623daa35a61a2833f.jpg",
    description: "Serious performance in a thin and light design.",
    features: [
      "M1 chip",
      "11-inch Liquid Retina display",
      "Touch ID in top button",
      "All-day battery life",
    ],
    inStock: true,
    stockQuantity: 25,
    tags: ["ipad", "air", "11-inch", "light"],
    rating: 4.5,
    reviews: 178,
  },
  {
    id: "ipad-mini",
    name: "iPad Mini",
    category: "ipad",
    price: 599.99,
    originalPrice: 649.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/1a/d1/68/1ad1686480720fb857d7f03113f82a99.jpg",
    description: "The full iPad experience designed to fit in one hand.",
    features: [
      "A15 Bionic chip",
      "8.3-inch Liquid Retina display",
      "Touch ID in top button",
      "5G capable",
    ],
    inStock: true,
    stockQuantity: 30,
    tags: ["ipad", "mini", "compact", "portable"],
    rating: 4.4,
    reviews: 156,
  },
  {
  id: "ipad-pro-13-m2",
  name: "iPad Pro 13-inch M2",
  category: "ipad",
  price: 1299.99,
  originalPrice: 1399.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/c4/12/d6/c412d6fb1efc804053522eb46bcb2fe4.jpg",
  description: "The ultimate iPad experience with M2 chip and stunning display.",
  features: [
    "M2 chip",
    "13-inch Liquid Retina XDR display",
    "Pro camera system with LiDAR",
    "Thunderbolt connectivity",
    "Face ID",
    "5G capable"
  ],
  inStock: true,
  stockQuantity: 15,
  tags: ["ipad", "pro", "13-inch", "powerful", "m2", "pro"],
  rating: 4.8,
  reviews: 134,
},
{
  id: "ipad-pro-13-m1",
  name: "iPad Pro 13-inch M1",
  category: "ipad",
  price: 1099.99,
  originalPrice: 1199.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/9e/0a/86/9e0a862d10abb8b907832effd9bb859d.jpg",
  description: "Professional tablet with M1 chip for creative work.",
  features: [
    "M1 chip",
    "13-inch Liquid Retina XDR display",
    "Pro camera system with LiDAR",
    "Thunderbolt connectivity",
    "Face ID"
  ],
  inStock: true,
  stockQuantity: 12,
  tags: ["ipad", "pro", "13-inch", "m1", "pro", "creative"],
  rating: 4.7,
  reviews: 98,
},
{
  id: "ipad-pro-11-m2",
  name: "iPad Pro 11-inch M2",
  category: "ipad",
  price: 999.99,
  originalPrice: 1099.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/cf/a6/41/cfa641b3023ec7dbdea9961b0c0171aa.jpg",
  description: "Compact pro performance with advanced features.",
  features: [
    "M2 chip",
    "11-inch Liquid Retina display",
    "Pro camera system",
    "5G capable",
    "Face ID"
  ],
  inStock: true,
  stockQuantity: 18,
  tags: ["ipad", "pro", "11-inch", "portable", "m2", "pro"],
  rating: 4.7,
  reviews: 189,
},
{
  id: "ipad-pro-11-m1",
  name: "iPad Pro 11-inch M1",
  category: "ipad",
  price: 849.99,
  originalPrice: 949.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/a3/e0/cc/a3e0ccd7674ba52c8489d14f2a80069d.jpg",
  description: "Powerful portable tablet with M1 chip.",
  features: [
    "M1 chip",
    "11-inch Liquid Retina display",
    "Pro camera system",
    "Face ID",
    "USB-C connectivity"
  ],
  inStock: true,
  stockQuantity: 14,
  tags: ["ipad", "pro", "11-inch", "m1", "pro", "portable"],
  rating: 4.6,
  reviews: 112,
},
{
  id: "ipad-air-13-m1",
  name: "iPad Air 13-inch M1",
  category: "ipad",
  price: 899.99,
  originalPrice: 999.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/61/bb/c9/61bbc95240e1d08000c2a8f1dd2037d7.jpg",
  description: "Powerful and versatile with M1 chip in colorful designs.",
  features: [
    "M1 chip",
    "13-inch Liquid Retina display",
    "Touch ID in top button",
    "5G capable",
    "6 color options"
  ],
  inStock: true,
  stockQuantity: 22,
  tags: ["ipad", "air", "13-inch", "versatile", "m1", "air"],
  rating: 4.6,
  reviews: 223,
},
{
  id: "ipad-air-13-a14",
  name: "iPad Air 13-inch A14",
  category: "ipad",
  price: 749.99,
  originalPrice: 849.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/9c/21/e0/9c21e03c16d53ee06b8fe269b807e3a4.jpg",
  description: "Large screen iPad Air with A14 Bionic chip.",
  features: [
    "A14 Bionic chip",
    "13-inch Liquid Retina display",
    "Touch ID in top button",
    "5G capable",
    "All-day battery life"
  ],
  inStock: true,
  stockQuantity: 16,
  tags: ["ipad", "air", "13-inch", "a14", "air", "value"],
  rating: 4.5,
  reviews: 145,
},
{
  id: "ipad-air-11-m1",
  name: "iPad Air 11-inch M1",
  category: "ipad",
  price: 699.99,
  originalPrice: 799.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/4f/8f/a0/4f8fa0ec30b93b9d364fa23c2e5c3836.jpg",
  description: "Serious performance in a thin and light design.",
  features: [
    "M1 chip",
    "11-inch Liquid Retina display",
    "Touch ID in top button",
    "All-day battery life",
    "5 color options"
  ],
  inStock: true,
  stockQuantity: 25,
  tags: ["ipad", "air", "11-inch", "light", "m1", "air"],
  rating: 4.5,
  reviews: 178,
},
{
  id: "ipad-air-11-a14",
  name: "iPad Air 11-inch A14",
  category: "ipad",
  price: 599.99,
  originalPrice: 699.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/3c/cf/13/3ccf1304ae21d39a14798b7120c138ed.jpg",
  description: "Compact and powerful iPad Air experience.",
  features: [
    "A14 Bionic chip",
    "11-inch Liquid Retina display",
    "Touch ID in top button",
    "5G capable",
    "Lightweight design"
  ],
  inStock: true,
  stockQuantity: 20,
  tags: ["ipad", "air", "11-inch", "a14", "air", "compact"],
  rating: 4.4,
  reviews: 134,
},
{
  id: "ipad-mini-6",
  name: "iPad Mini 6th Gen",
  category: "ipad",
  price: 599.99,
  originalPrice: 649.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/39/4b/98/394b988153b63e61c956f70a716aabdb.jpg",
  description: "The full iPad experience designed to fit in one hand.",
  features: [
    "A15 Bionic chip",
    "8.3-inch Liquid Retina display",
    "Touch ID in top button",
    "5G capable",
    "4 color options"
  ],
  inStock: true,
  stockQuantity: 30,
  tags: ["ipad", "mini", "compact", "portable", "a15", "mini"],
  rating: 4.4,
  reviews: 156,
},
{
  id: "ipad-mini-5",
  name: "iPad Mini 5th Gen",
  category: "ipad",
  price: 449.99,
  originalPrice: 499.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/52/b4/6d/52b46d84642f447c92b89eb93518330c.jpg",
  description: "Compact tablet with powerful A12 chip.",
  features: [
    "A12 Bionic chip",
    "7.9-inch Retina display",
    "Touch ID",
    "Apple Pencil support",
    "Lightweight design"
  ],
  inStock: true,
  stockQuantity: 18,
  tags: ["ipad", "mini", "compact", "a12", "mini", "budget"],
  rating: 4.3,
  reviews: 89,
},
{
  id: "ipad-10th-gen",
  name: "iPad 10th Generation",
  category: "ipad",
  price: 449.99,
  originalPrice: 499.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/53/15/f6/5315f613d01cb4c67a84cf5957db3eac.jpg",
  description: "All-screen design with powerful A14 chip.",
  features: [
    "A14 Bionic chip",
    "10.9-inch Liquid Retina display",
    "Touch ID in top button",
    "5G capable",
    "4 color options"
  ],
  inStock: true,
  stockQuantity: 35,
  tags: ["ipad", "standard", "10th-gen", "a14", "value"],
  rating: 4.5,
  reviews: 267,
},
{
  id: "ipad-9th-gen",
  name: "iPad 9th Generation",
  category: "ipad",
  price: 329.99,
  originalPrice: 379.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/ab/d3/e9/abd3e97626ac173ee0d230a9b77b8a4d.jpg",
  description: "Popular iPad with A13 chip and Retina display.",
  features: [
    "A13 Bionic chip",
    "10.2-inch Retina display",
    "Touch ID",
    "Apple Pencil support",
    "All-day battery life"
  ],
  inStock: true,
  stockQuantity: 28,
  tags: ["ipad", "standard", "9th-gen", "a13", "budget"],
  rating: 4.4,
  reviews: 312,
},
{
  id: "ipad-pro-13-cellular",
  name: "iPad Pro 13-inch Cellular",
  category: "ipad",
  price: 1499.99,
  originalPrice: 1599.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/71/96/c7/7196c7705bd3849718923e3ac0f04e53.jpg",
  description: "Pro tablet with cellular connectivity for on-the-go work.",
  features: [
    "M2 chip",
    "13-inch Liquid Retina XDR display",
    "5G cellular connectivity",
    "1TB storage option",
    "Face ID"
  ],
  inStock: true,
  stockQuantity: 8,
  tags: ["ipad", "pro", "13-inch", "cellular", "5g", "pro"],
  rating: 4.8,
  reviews: 67,
},
{
  id: "ipad-air-13-cellular",
  name: "iPad Air 13-inch Cellular",
  category: "ipad",
  price: 1099.99,
  originalPrice: 1199.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/51/0d/32/510d32df2bc5460a249e916858afe0d3.jpg",
  description: "Large screen iPad Air with cellular connectivity.",
  features: [
    "M1 chip",
    "13-inch Liquid Retina display",
    "5G cellular connectivity",
    "Touch ID in top button",
    "256GB storage"
  ],
  inStock: true,
  stockQuantity: 12,
  tags: ["ipad", "air", "13-inch", "cellular", "5g", "air"],
  rating: 4.6,
  reviews: 78,
},
{
  id: "ipad-mini-cellular",
  name: "iPad Mini Cellular",
  category: "ipad",
  price: 749.99,
  originalPrice: 799.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/c9/58/0e/c9580e0a824564bb28c26693a42bb637.jpg",
  description: "Compact tablet with cellular connectivity.",
  features: [
    "A15 Bionic chip",
    "8.3-inch Liquid Retina display",
    "5G cellular connectivity",
    "Touch ID in top button",
    "Portable design"
  ],
  inStock: true,
  stockQuantity: 15,
  tags: ["ipad", "mini", "cellular", "5g", "mini", "portable"],
  rating: 4.5,
  reviews: 92,
},

  // Watch Category (4 products)
  {
    id: "watch-series-10",
    name: "Apple Watch Series 10",
    category: "watch",
    price: 449.99,
    originalPrice: 499.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/4f/45/44/4f45446240142a09e6639087445592a5.jpg",
    description:
      "The most advanced Apple Watch with innovative health features.",
    features: [
      "Advanced health monitoring",
      "Crash Detection and Fall Detection",
      "Water resistant 50m",
      "GPS + Cellular",
    ],
    inStock: true,
    stockQuantity: 35,
    tags: ["watch", "series-10", "health", "premium"],
    rating: 4.7,
    reviews: 289,
  },
  {
    id: "watch-ultra-3",
    name: "Apple Watch Ultra 3",
    category: "watch",
    price: 849.99,
    originalPrice: 899.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/6a/b4/26/6ab42674367ab3d57ca666dd650ef4d0.jpg",
    description: "The ultimate sports watch for extreme adventures.",
    features: [
      "Rugged titanium case",
      "Dual-frequency GPS",
      "Depth gauge and water temperature sensor",
      "Action button for quick workouts",
    ],
    inStock: true,
    stockQuantity: 12,
    tags: ["watch", "ultra", "sports", "adventure"],
    rating: 4.9,
    reviews: 134,
  },
  {
    id: "watch-se-2",
    name: "Apple Watch SE (2nd Gen)",
    category: "watch",
    price: 299.99,
    originalPrice: 329.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/06/e9/d5/06e9d5babcfd0b5beda722791d225abc.jpg",
    description:
      "Essential features and affordable price in three stylish cases.",
    features: [
      "Essential health and safety features",
      "Fast charging",
      "Swimproof design",
      "Family Setup capable",
    ],
    inStock: true,
    stockQuantity: 40,
    tags: ["watch", "se", "budget", "essential"],
    rating: 4.3,
    reviews: 267,
  },
  {
    id: "watch-series-9",
    name: "Apple Watch Series 9",
    category: "watch",
    price: 399.99,
    originalPrice: 429.99,
    currency: "USD",
    image: "https://i.pinimg.com/1200x/25/e3/5d/25e35d0737f7c134667fdda1b641bdb7.jpg",
    description: "Smarter, brighter, and more powerful than ever.",
    features: [
      "Double tap gesture control",
      "Brighter display",
      "On-device Siri",
      "Precision Finding for iPhone",
    ],
    inStock: true,
    stockQuantity: 20,
    tags: ["watch", "series-9", "feature-rich", "popular"],
    rating: 4.6,
    reviews: 198,
  },
  {
  id: "watch-series-10-gps",
  name: "Apple Watch Series 10 GPS",
  category: "watch",
  price: 399.99,
  originalPrice: 449.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/df/9f/1a/df9f1a28b0547853465b641b4ec364a9.jpg",
  description: "The most advanced Apple Watch with innovative health features.",
  features: [
    "Advanced health monitoring",
    "Crash Detection and Fall Detection",
    "Water resistant 50m",
    "GPS connectivity",
    "18 hours battery life"
  ],
  inStock: true,
  stockQuantity: 35,
  tags: ["watch", "series-10", "health", "premium", "gps", "series-10"],
  rating: 4.7,
  reviews: 289,
},
{
  id: "watch-series-10-cellular",
  name: "Apple Watch Series 10 Cellular",
  category: "watch",
  price: 499.99,
  originalPrice: 549.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/bf/de/2d/bfde2d332b10d081b1a7d7760580ca6f.jpg",
  description: "Stay connected without your iPhone with cellular model.",
  features: [
    "Cellular connectivity",
    "Advanced health monitoring",
    "Crash Detection and Fall Detection",
    "Water resistant 50m",
    "GPS + Cellular"
  ],
  inStock: true,
  stockQuantity: 25,
  tags: ["watch", "series-10", "cellular", "premium", "connected", "series-10"],
  rating: 4.8,
  reviews: 167,
},
{
  id: "watch-ultra-3-titanium",
  name: "Apple Watch Ultra 3 Titanium",
  category: "watch",
  price: 799.99,
  originalPrice: 849.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/5b/12/ea/5b12ea207763e04d14a4ea57236e7df4.jpg",
  description: "The ultimate sports watch for extreme adventures.",
  features: [
    "Rugged titanium case",
    "Dual-frequency GPS",
    "Depth gauge and water temperature sensor",
    "Action button for quick workouts",
    "36 hours battery life"
  ],
  inStock: true,
  stockQuantity: 12,
  tags: ["watch", "ultra", "sports", "adventure", "titanium", "ultra"],
  rating: 4.9,
  reviews: 134,
},
{
  id: "watch-ultra-2",
  name: "Apple Watch Ultra 2",
  category: "watch",
  price: 749.99,
  originalPrice: 799.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/fa/90/db/fa90dbe231b595a4d17561ec9b00ec3f.jpg",
  description: "Advanced adventure watch with premium features.",
  features: [
    "Rugged titanium case",
    "Dual-frequency GPS",
    "Depth gauge",
    "Action button",
    "36 hours battery life"
  ],
  inStock: true,
  stockQuantity: 15,
  tags: ["watch", "ultra", "sports", "adventure", "ultra-2", "ultra"],
  rating: 4.8,
  reviews: 89,
},
{
  id: "watch-series-9-gps",
  name: "Apple Watch Series 9 GPS",
  category: "watch",
  price: 349.99,
  originalPrice: 399.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/7d/31/67/7d3167d6281c71b92392e852ba12a7d1.jpg",
  description: "Smarter, brighter, and more powerful than ever.",
  features: [
    "Double tap gesture control",
    "Brighter display",
    "On-device Siri",
    "Precision Finding for iPhone",
    "18 hours battery life"
  ],
  inStock: true,
  stockQuantity: 28,
  tags: ["watch", "series-9", "feature-rich", "popular", "gps", "series-9"],
  rating: 4.6,
  reviews: 198,
},
{
  id: "watch-series-9-cellular",
  name: "Apple Watch Series 9 Cellular",
  category: "watch",
  price: 449.99,
  originalPrice: 499.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/a8/f4/c5/a8f4c5d79c056d3c565f0b3473dafb25.jpg",
  description: "Feature-rich watch with cellular connectivity.",
  features: [
    "Cellular connectivity",
    "Double tap gesture control",
    "Brighter display",
    "On-device Siri",
    "GPS + Cellular"
  ],
  inStock: true,
  stockQuantity: 22,
  tags: ["watch", "series-9", "cellular", "feature-rich", "series-9"],
  rating: 4.7,
  reviews: 145,
},
{
  id: "watch-se-2-gps",
  name: "Apple Watch SE (2nd Gen) GPS",
  category: "watch",
  price: 249.99,
  originalPrice: 279.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/5b/bb/8e/5bbb8ee93b5f036de90d10651beaaac4.jpg",
  description: "Essential features and affordable price.",
  features: [
    "Essential health and safety features",
    "Fast charging",
    "Swimproof design",
    "Family Setup capable",
    "18 hours battery life"
  ],
  inStock: true,
  stockQuantity: 40,
  tags: ["watch", "se", "budget", "essential", "gps", "se"],
  rating: 4.3,
  reviews: 267,
},
{
  id: "watch-se-2-cellular",
  name: "Apple Watch SE (2nd Gen) Cellular",
  category: "watch",
  price: 299.99,
  originalPrice: 329.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/ee/3d/3c/ee3d3c285e2b88b262d54d057471d39f.jpg",
  description: "Affordable watch with cellular connectivity.",
  features: [
    "Cellular connectivity",
    "Essential health features",
    "Swimproof design",
    "Family Setup capable",
    "GPS + Cellular"
  ],
  inStock: true,
  stockQuantity: 32,
  tags: ["watch", "se", "budget", "cellular", "value", "se"],
  rating: 4.4,
  reviews: 178,
},
{
  id: "watch-series-8",
  name: "Apple Watch Series 8",
  category: "watch",
  price: 299.99,
  originalPrice: 349.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/2b/51/8f/2b518f2838ef973586533ac0d5cbed98.jpg",
  description: "Advanced health features with temperature sensing.",
  features: [
    "Temperature sensing",
    "Crash Detection",
    "Cycle tracking",
    "Water resistant 50m",
    "18 hours battery life"
  ],
  inStock: true,
  stockQuantity: 18,
  tags: ["watch", "series-8", "health", "temperature", "series-8"],
  rating: 4.5,
  reviews: 156,
},
{
  id: "watch-nike-series-9",
  name: "Apple Watch Nike Series 9",
  category: "watch",
  price: 379.99,
  originalPrice: 429.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/08/d0/f9/08d0f9acf864df5dd31031f908c59ad2.jpg",
  description: "Designed for athletes with exclusive Nike watch faces.",
  features: [
    "Nike Sport Band",
    "Exclusive Nike watch faces",
    "Double tap gesture control",
    "GPS connectivity",
    "Nike Run Club integration"
  ],
  inStock: true,
  stockQuantity: 14,
  tags: ["watch", "series-9", "nike", "sports", "athlete", "series-9"],
  rating: 4.6,
  reviews: 98,
},
{
  id: "watch-hermes-series-10",
  name: "Apple Watch Hermès Series 10",
  category: "watch",
  price: 1299.99,
  originalPrice: 1399.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/00/b3/83/00b38337581e2693b806245944ba9475.jpg",
  description: "Luxury timepiece with exclusive Hermès designs.",
  features: [
    "Hermès leather bands",
    "Exclusive Hermès watch faces",
    "Premium packaging",
    "Cellular connectivity",
    "Limited edition designs"
  ],
  inStock: true,
  stockQuantity: 6,
  tags: ["watch", "series-10", "hermes", "luxury", "premium", "series-10"],
  rating: 4.9,
  reviews: 45,
},
{
  id: "watch-kids-edition",
  name: "Apple Watch Kids Edition",
  category: "watch",
  price: 199.99,
  originalPrice: 229.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/1f/83/d6/1f83d656bd5e13ec2bd39292dc1d014d.jpg",
  description: "Designed for kids with Family Setup and parental controls.",
  features: [
    "Family Setup capable",
    "Schooltime mode",
    "Parental controls",
    "Durable design",
    "Fun colors"
  ],
  inStock: true,
  stockQuantity: 25,
  tags: ["watch", "kids", "family", "durable", "educational", "kids"],
  rating: 4.4,
  reviews: 112,
},

  // AirPods Category (3 products)
  {
    id: "airpods-pro-3",
    name: "AirPods Pro (3rd Gen)",
    category: "airpods",
    price: 279.99,
    originalPrice: 299.99,
    currency: "USD",
    image: "https://i.pinimg.com/736x/1f/8f/f9/1f8ff9939c356c8cd36bfdc5a9f65fd2.jpg",
    description:
      "Active Noise Cancellation and Adaptive Transparency for immersive sound.",
    features: [
      "Active Noise Cancellation 2.0",
      "Adaptive Audio and Conversation Awareness",
      "Sweat and water resistant (IP54)",
      "MagSafe Charging Case with speaker",
    ],
    inStock: true,
    stockQuantity: 45,
    tags: ["airpods", "pro", "noise-cancellation", "premium"],
    rating: 4.8,
    reviews: 312,
  },
  {
    id: "airpods-4",
    name: "AirPods (4th Gen)",
    category: "airpods",
    price: 179.99,
    originalPrice: 199.99,
    currency: "USD",
    image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=500",
    description: "The perfect introduction to the AirPods experience.",
    features: [
      "Rich, high-quality audio",
      "Long battery life with charging case",
      "Quick and easy setup",
      "Sweat and water resistant",
    ],
    inStock: true,
    stockQuantity: 60,
    tags: ["airpods", "standard", "wireless", "popular"],
    rating: 4.5,
    reviews: 445,
  },
  {
    id: "airpods-max-2",
    name: "AirPods Max (2nd Gen)",
    category: "airpods",
    price: 599.99,
    originalPrice: 649.99,
    currency: "USD",
    image: "https://i.pinimg.com/736x/eb/af/16/ebaf16a09cfbc6bf07f30e2136107574.jpg",
    description: "A perfect balance of exhilarating high-fidelity audio.",
    features: [
      "High-fidelity audio with Adaptive EQ",
      "Active Noise Cancellation with Transparency mode",
      "Spatial audio with dynamic head tracking",
      "Breathable knit-mesh canopy",
    ],
    inStock: true,
    stockQuantity: 8,
    tags: ["airpods", "max", "over-ear", "premium"],
    rating: 4.7,
    reviews: 89,
  },
  {
  id: "airpods-pro-3",
  name: "AirPods Pro (3rd Gen)",
  category: "airpods",
  price: 279.99,
  originalPrice: 299.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/1c/27/b9/1c27b93a3d266294994944c471beb07a.jpg",
  description: "Active Noise Cancellation and Adaptive Transparency for immersive sound.",
  features: [
    "Active Noise Cancellation 2.0",
    "Adaptive Audio and Conversation Awareness",
    "Sweat and water resistant (IP54)",
    "MagSafe Charging Case with speaker",
    "Personalized Spatial Audio"
  ],
  inStock: true,
  stockQuantity: 45,
  tags: ["airpods", "pro", "noise-cancellation", "premium"],
  rating: 4.8,
  reviews: 312,
},
{
  id: "airpods-pro-2",
  name: "AirPods Pro (2nd Gen)",
  category: "airpods",
  price: 229.99,
  originalPrice: 249.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/81/a2/07/81a20722a03d3cfb24c11b9d9470e62d.jpg",
  description: "Advanced noise cancellation with improved sound quality.",
  features: [
    "Active Noise Cancellation",
    "Transparency mode",
    "Sweat and water resistant",
    "Wireless Charging Case",
    "Hey Siri support"
  ],
  inStock: true,
  stockQuantity: 32,
  tags: ["airpods", "pro", "noise-cancellation", "value"],
  rating: 4.7,
  reviews: 189,
},
{
  id: "airpods-pro-1",
  name: "AirPods Pro (1st Gen)",
  category: "airpods",
  price: 199.99,
  originalPrice: 219.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/e0/ad/3e/e0ad3ec225c1801ddbad74600ac4b87e.jpg",
  description: "The original AirPods Pro with active noise cancellation.",
  features: [
    "Active Noise Cancellation",
    "Transparency mode",
    "Sweat and water resistant",
    "Wireless Charging Case",
    "Adaptive EQ"
  ],
  inStock: true,
  stockQuantity: 18,
  tags: ["airpods", "pro", "noise-cancellation", "budget"],
  rating: 4.5,
  reviews: 267,
},
{
  id: "airpods-4",
  name: "AirPods (4th Gen)",
  category: "airpods",
  price: 179.99,
  originalPrice: 199.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/29/df/d0/29dfd064568fec0b11f8fbe71dd95b86.jpg",
  description: "The perfect introduction to the AirPods experience.",
  features: [
    "Rich, high-quality audio",
    "Long battery life with charging case",
    "Quick and easy setup",
    "Sweat and water resistant"
  ],
  inStock: true,
  stockQuantity: 60,
  tags: ["airpods", "standard", "wireless", "popular"],
  rating: 4.5,
  reviews: 445,
},
{
  id: "airpods-3",
  name: "AirPods (3rd Gen)",
  category: "airpods",
  price: 149.99,
  originalPrice: 169.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/d4/a8/d1/d4a8d19272b4f188cf21276145736c84.jpg",
  description: "Spatial audio with dynamic head tracking for immersive sound.",
  features: [
    "Spatial audio with dynamic head tracking",
    "Sweat and water resistant",
    "MagSafe Charging Case",
    "Force sensor control"
  ],
  inStock: true,
  stockQuantity: 42,
  tags: ["airpods", "standard", "spatial-audio", "value"],
  rating: 4.4,
  reviews: 312,
},
{
  id: "airpods-2",
  name: "AirPods (2nd Gen)",
  category: "airpods",
  price: 129.99,
  originalPrice: 149.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/ad/f7/61/adf7612f7855038988972c4739ec9ba0.jpg",
  description: "Classic AirPods with wireless charging case.",
  features: [
    "Wireless Charging Case",
    "Hey Siri support",
    "Quick and easy setup",
    "All-day battery life"
  ],
  inStock: true,
  stockQuantity: 28,
  tags: ["airpods", "standard", "wireless", "classic"],
  rating: 4.3,
  reviews: 278,
},
{
  id: "airpods-max-2",
  name: "AirPods Max (2nd Gen)",
  category: "airpods",
  price: 599.99,
  originalPrice: 649.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/2f/ee/01/2fee012d4b502c1c81631f9c4e211bd2.jpg",
  description: "A perfect balance of exhilarating high-fidelity audio.",
  features: [
    "High-fidelity audio with Adaptive EQ",
    "Active Noise Cancellation with Transparency mode",
    "Spatial audio with dynamic head tracking",
    "Breathable knit-mesh canopy"
  ],
  inStock: true,
  stockQuantity: 8,
  tags: ["airpods", "max", "over-ear", "premium"],
  rating: 4.7,
  reviews: 89,
},
{
  id: "airpods-max-1",
  name: "AirPods Max (1st Gen)",
  category: "airpods",
  price: 499.99,
  originalPrice: 549.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/12/38/fe/1238fe2b016f40b13aa9c0d77bde9278.jpg",
  description: "Premium over-ear headphones with exceptional sound quality.",
  features: [
    "High-fidelity audio",
    "Active Noise Cancellation",
    "Spatial audio",
    "Premium materials"
  ],
  inStock: true,
  stockQuantity: 12,
  tags: ["airpods", "max", "over-ear", "luxury"],
  rating: 4.6,
  reviews: 145,
},
{
  id: "airpods-pro-special",
  name: "AirPods Pro Special Edition",
  category: "airpods",
  price: 299.99,
  originalPrice: 329.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/c8/cd/eb/c8cdebd5a2f616c342acb93adb17f515.jpg",
  description: "Limited edition AirPods Pro with exclusive features.",
  features: [
    "Limited edition design",
    "Active Noise Cancellation 2.0",
    "Exclusive charging case",
    "Special engraving options"
  ],
  inStock: true,
  stockQuantity: 15,
  tags: ["airpods", "pro", "special-edition", "limited"],
  rating: 4.8,
  reviews: 67,
},
{
  id: "airpods-wireless-case",
  name: "AirPods with Wireless Charging Case",
  category: "airpods",
  price: 169.99,
  originalPrice: 189.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/2c/a4/24/2ca4249520842c26215b04daf8e1a919.jpg",
  description: "AirPods with convenient wireless charging case.",
  features: [
    "Wireless Charging Case",
    "Quick and easy setup",
    "All-day battery life",
    "Sweat and water resistant"
  ],
  inStock: true,
  stockQuantity: 35,
  tags: ["airpods", "standard", "wireless-charging", "convenient"],
  rating: 4.4,
  reviews: 198,
},
{
  id: "airpods-lightning-case",
  name: "AirPods with Lightning Charging Case",
  category: "airpods",
  price: 139.99,
  originalPrice: 159.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/ad/12/51/ad1251ba243873492368e2c4faf89320.jpg",
  description: "Classic AirPods with Lightning charging case.",
  features: [
    "Lightning Charging Case",
    "Quick and easy setup",
    "All-day battery life",
    "Universal compatibility"
  ],
  inStock: true,
  stockQuantity: 40,
  tags: ["airpods", "standard", "lightning", "budget"],
  rating: 4.3,
  reviews: 234,
},
{
  id: "airpods-kids",
  name: "AirPods Kids Edition",
  category: "airpods",
  price: 149.99,
  originalPrice: 169.99,
  currency: "USD",
  image: "https://i.pinimg.com/1200x/4a/20/aa/4a20aa7357b1b0c34df7f986fcf5da9a.jpg",
  description: "Designed for kids with volume limiting and durable design.",
  features: [
    "Volume limiting for kids",
    "Durable design",
    "Fun colors",
    "All-day battery life"
  ],
  inStock: true,
  stockQuantity: 22,
  tags: ["airpods", "kids", "durable", "family"],
  rating: 4.5,
  reviews: 112,
},
{
  id: "airpods-sports",
  name: "AirPods Sports Edition",
  category: "airpods",
  price: 199.99,
  originalPrice: 219.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/08/50/47/0850476509d686f921a59f41a781237e.jpg",
  description: "Designed for athletes with secure fit and sweat resistance.",
  features: [
    "Secure fit for sports",
    "Enhanced sweat resistance",
    "Quick charging",
    "Sport-specific EQ"
  ],
  inStock: true,
  stockQuantity: 18,
  tags: ["airpods", "sports", "sweat-resistant", "athlete"],
  rating: 4.6,
  reviews: 89,
},
{
  id: "airpods-business",
  name: "AirPods Business Edition",
  category: "airpods",
  price: 249.99,
  originalPrice: 269.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/90/f5/63/90f5630f58f649a29a3228551caee5a4.jpg",
  description: "Optimized for business calls and meetings.",
  features: [
    "Enhanced voice isolation",
    "Long battery life for calls",
    "Professional design",
    "Meeting optimization"
  ],
  inStock: true,
  stockQuantity: 14,
  tags: ["airpods", "business", "professional", "calls"],
  rating: 4.7,
  reviews: 76,
},
{
  id: "airpods-travel",
  name: "AirPods Travel Edition",
  category: "airpods",
  price: 219.99,
  originalPrice: 239.99,
  currency: "USD",
  image: "https://i.pinimg.com/736x/58/c0/7a/58c07a23c902739526744f122c45d73a.jpg",
  description: "Perfect for travelers with noise cancellation and long battery.",
  features: [
    "Travel-friendly case",
    "Extended battery life",
    "Noise cancellation",
    "Compact design"
  ],
  inStock: true,
  stockQuantity: 16,
  tags: ["airpods", "travel", "noise-cancellation", "portable"],
  rating: 4.5,
  reviews: 98,
},


];
